### ISSUE TITLE
Restore skipped acceptance tests

### ISSUE THREAD

**Issue by jmcarp** [18F/cg-atlas#189]
A few bugs in the cf acceptance tests mean that we need to skip some some broken tests for now:

* The SSO tests are failing because they send requests to the api url without a protocol and don't follow redirects, so that we get 301s instead of 200s. We can restore these tests once https://github.com/cloudfoundry/cf-acceptance-tests/pull/155 or another fix is merged and released.
* The dotnet-core buildpack detection test is failing because the dotnet app bundled with the acceptance tests doesn't work. We can restore this test once https://github.com/cloudfoundry/cf-acceptance-tests/pull/152 is merged and released.
* The encoding test is failing because the test relies on passing a double quote through to the app, which the most recent version of tomcat (8.0.39 at time of writing) no longer allows.  The current version of the buildpack (v3.10 at time of writing) uses this version of tomcast by default. We can restore this test once https://github.com/cloudfoundry/java-buildpack/issues/355 is fixed.

To revert, we'll drop the following lines from the acceptance test secrets:

```yaml
properties:
  acceptance_tests:
    include_sso: false
    skip_regex: 'dotnet\-core|transparently\sproxies\sboth\sreserved\scharacters\sand\sunsafe\scharacters'
```
